# Generated by Django 2.2.4 on 2019-09-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('avg_value', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weather_date', models.DateField(unique=True)),
                ('precipitation', models.CharField(default='', max_length=5)),
                ('cloud_cover', models.CharField(default='', max_length=5)),
                ('events', models.CharField(default='', max_length=5)),
                ('wind_dir_degrees', models.CharField(default='', max_length=5)),
                ('dew', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather_app.WeatherCharacteristic')),
                ('humidity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather_app.WeatherCharacteristic')),
                ('sea_level_pressure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather_app.WeatherCharacteristic')),
                ('temperature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather_app.WeatherCharacteristic')),
                ('visibility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather_app.WeatherCharacteristic')),
                ('wind_velocity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather_app.WeatherCharacteristic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
