# Generated by Django 2.2.4 on 2019-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('max_humd', models.IntegerField()),
                ('min_humd', models.IntegerField()),
                ('mean_humd', models.IntegerField()),
            ],
        ),
    ]
