# Generated by Django 2.2.4 on 2019-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_auto_20190909_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='file_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='avg_humd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='avg_max_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='avg_min_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='max_humd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='max_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='mean_humd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='min_humd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='min_temp',
            field=models.IntegerField(default=0),
        ),
    ]
