# Generated by Django 2.2.4 on 2019-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_auto_20190909_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='avg_humd',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='avg_max_temp',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='avg_min_temp',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='max_humd',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='max_temp',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='mean_humd',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='min_humd',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='min_temp',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
