# Generated by Django 2.2.4 on 2019-09-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_auto_20190909_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileData',
        ),
    ]
