# Generated by Django 2.2.4 on 2019-09-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0008_auto_20190909_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='avg_humd',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='avg_max_temp',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='avg_min_temp',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='max_humd',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='max_temp',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='mean_humd',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='min_humd',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='min_temp',
        ),
    ]
