# Generated by Django 2.2.4 on 2019-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0010_auto_20190910_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileData',
        ),
    ]
