# Generated by Django 2.2.4 on 2019-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_app', '0011_delete_filedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=200)),
                ('max_temp', models.IntegerField(default=0)),
                ('min_temp', models.IntegerField(default=0)),
                ('max_humd', models.IntegerField(default=0)),
                ('min_humd', models.IntegerField(default=0)),
                ('mean_humd', models.IntegerField(default=0)),
                ('avg_max_temp', models.IntegerField(default=0)),
                ('avg_min_temp', models.IntegerField(default=0)),
                ('avg_humd', models.IntegerField(default=0)),
            ],
        ),
    ]
