# Generated by Django 2.2.4 on 2019-09-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0012_filedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='avg_humd',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='avg_max_temp',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='avg_min_temp',
        ),
    ]
